# Generated by Django 2.1.2 on 2018-10-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Джедай',
                'verbose_name_plural': 'Джедаи',
            },
        ),
        migrations.CreateModel(
            name='Padawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Падаван',
                'verbose_name_plural': 'Падаваны',
            },
        ),
        migrations.CreateModel(
            name='PadawanAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Ответ падавана',
                'verbose_name_plural': 'Ответы падавана',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True, max_length=300)),
                ('answer', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, unique=True)),
                ('questions', models.ManyToManyField(db_index=True, to='Jedi.Question')),
            ],
        ),
        migrations.AddField(
            model_name='padawananswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jedi.Question'),
        ),
        migrations.AddField(
            model_name='padawan',
            name='answers',
            field=models.ManyToManyField(to='Jedi.PadawanAnswer'),
        ),
        migrations.AddField(
            model_name='padawan',
            name='master',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Jedi.Jedi', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='padawan',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jedi.Planet'),
        ),
        migrations.AddField(
            model_name='jedi',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jedi.Planet'),
        ),
    ]
