# Generated by Django 2.1.2 on 2018-10-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jedi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padawan',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jedi.Jedi', verbose_name='Мастер'),
        ),
    ]
