# Generated by Django 2.1.2 on 2018-10-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jedi', '0002_auto_20181018_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padawan',
            name='answers',
        ),
        migrations.AddField(
            model_name='padawananswer',
            name='padawan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Jedi.Padawan'),
        ),
    ]
