# Generated by Django 2.1.2 on 2018-10-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jedi', '0003_auto_20181018_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='padawan',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Jedi.Test'),
        ),
    ]
