# Generated by Django 2.1.2 on 2018-10-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jedi', '0006_auto_20181019_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padawan',
            name='test',
        ),
    ]
