# Generated by Django 2.1.2 on 2018-10-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jedi', '0007_remove_padawan_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='padawan',
            name='test',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jedi.Test'),
        ),
    ]
